### ISSUE TITLE
Can't see text selection highlight

### ISSUE THREAD

**Issue by etmoore** [colindean/atom-zenburn#8]
using 2.0.1 with Atom 0.184.0
When I select text, I can't see the highlight. The text is selected, but there's no visual indication.

**Comment by colindean** [comment]
Oh snap. I'll look into it, and perhaps @arnaudsj can, too.

**Comment by colindean** [comment]
Selection is handled [here](https://github.com/colindean/atom-zenburn/blob/master/stylesheets/base.less#L47):

```
atom-text-editor.is-focused .selection .region {
  background-color: @syntax-selection-color;
}
```

It looks like `.selection` changed to `.has-selection`, but I can't find `.region` anymore.

**Comment by colindean** [comment]
I'm pretty sure I fixed it. Now working for me. If you could pull down HEAD and check it out, great. If not, I'll just release 2.0.2 and you can check that.

**Comment by etmoore** [comment]
@colindean - I'm not sure how to pull down HEAD... sorry! Can you release 2.0.2?

**Comment by colindean** [comment]
Done.

**Comment by etmoore** [comment]
You da man. Glad to have my favorite theme back :smile:

**Comment by colindean** [comment]
:beers:
